import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import TopNavTitleContextProvider from "@/components/providers/TopNavTitleContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const runtime = "edge";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50`}>
        <div className="mx-auto flex min-h-dvh max-w-lg flex-col bg-white shadow-lg">
          <TopNavTitleContextProvider>
            <TopNav />
            {children}
          </TopNavTitleContextProvider>
        </div>
      </body>
    </html>
  );
}
