import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import TopNavTitleContextProvider from "@/components/providers/TopNavTitleContextProvider";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";
import { headers } from "next/headers";
import { isValidLanguage } from "@/lib/dictionaries";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const runtime = "edge";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const langFromHeader = headers().get("x-pathname")?.split("/")?.[1] ?? "";
  const language = isValidLanguage(langFromHeader) ? langFromHeader : "en";
  return (
    <html lang={language} dir={language === "he" ? "rtl" : "ltr"}>
      <body className={`${inter.className} bg-slate-50`}>
        <div className="mx-auto flex min-h-dvh max-w-lg flex-col bg-white shadow-lg">
          <TopNavTitleContextProvider>
            <TopNav language={language} />
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </TopNavTitleContextProvider>
        </div>
      </body>
    </html>
  );
}
